from pathlib import Path

DATA_ROOT = Path("/Users/samsonho/KSL/data/Ground_truth")

DATASETS = [
    "DS30-GCaMP8f-m-V1",
    "DS31-GCaMP8m-m-V1",
    "DS32-GCaMP8s-m-V1",
]

SEED = 42

TRAIN_RATIO = 0.80
VAL_RATIO = 0.10
TEST_RATIO = 0.10

WINDOW_SIZE = 64
HALF_WINDOW = WINDOW_SIZE // 2

SIGMA_SEC = 0.05
FRAME_RATE = 30.0

EPS = 1e-8

BATCH_SIZE = 32
EVAL_BATCH_SIZE = 16384
NUM_EPOCHS = 30
LEARNING_RATE = 1e-3
DROP_LAST_TRAIN_BATCH = False
USE_AMP = True
PIN_MEMORY = True
PREFETCH_BATCHES = 2
SHOW_PROGRESS = True

MODEL_SAVE_PATH = "best_model.pt"

ISOLATED_AP_MIN_INTERVAL_SEC = 0.5
ISOLATED_AP_LOCAL_RADIUS_FRAMES = 3
ISOLATED_AP_THRESHOLD = 1.0
